### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by bastbnl** [flyingcircusio/pycountry#10]
Hi,

I noticed some super minor code updates on the README and older statements on the project page on pypi. PR coming up

**Comment by bastbnl** [comment]
Intended to fix the bitbucket repo link too, but that was already fixed. Added specific lookup instead of global via `_` in PR #11

**Comment by dwasss** [comment]
Nice! A related question for you: if I have a bunch of country names I want translated, say in a pandas dataframe or in an array, how would I do that? I tried creating a tuple but the strings did not get translated.

**Comment by ctheune** [comment]
Thanks for those insights - I'm closing this as the PR was merged and you figured out the other answer yourself. :)
