### ISSUE TITLE
Adding Kosovo?

### ISSUE THREAD

**Issue by grischard** [flyingcircusio/pycountry#100]
Kosovo is a [partially recognised](https://en.wikipedia.org/wiki/International_recognition_of_Kosovo) state. XK is a "user assigned" ISO 3166 code not designated by the standard, but used by the European Commission, Switzerland, the Deutsche Bundesbank and other organisations.

Not having Kosovo in pycountry leads to bugs in software that depends on pycountry, for example in Home Assistant where the list of radio stations shows Kosovo as XK instead of Kosovo.

The Readme says:

> No changes to the data will be accepted into pycountry. This is a pure wrapper around the ISO standard using the pkg-isocodes database from Debian as is. If you need changes to the political situation in the world, please talk to the ISO or Debian people, not me.

Am I correct in understanding that you do not wish to add Kosovo at this time?

**Comment by ctheune** [comment]
Yes. This is a spare time project providing a wrapper around the databases that are maintained by Debian. Any changes to the database must come through the Debian repository. Please contact them here:
https://salsa.debian.org/iso-codes-team/iso-codes
