### ISSUE TITLE
Italian city fix

### ISSUE THREAD

**Issue by angel-acao** [flyingcircusio/pycountry#102]
Hi, 
For italian city The description of the province "Val d'Aoste" is wrong: the correct description is "Aosta". Because it is the region called "Valle d'Aosta" not the province. Furthermore, the coding of the province is not correct (IT-23). Correct coding must be "IT-AO"
thank you

**Comment by ctheune** [comment]
please report this with the upstream pkg-isocodes project, thanks!

**Comment by AcaoAngel** [comment]
Hi, I have tried to reach them directly but they have blocked the "new issue" functionality for non-members of their project. I tried to sign up and my request was rejected. Would you maybe have access to reach them?
