### ISSUE TITLE
Supported operating systems?

### ISSUE THREAD

**Issue by bede** [flyingcircusio/pycountry#114]
Pycountry seems to be working great on Linux and MacOS, but we're also testing Windows builds and running into issues. I can find no mention of OS support in this repo or its issues, so I wondered if Pycountry's OS support could be clarified.

Thanks!

**Comment by nschimmoller** [comment]
@bede it will be helpful if you could provide what errors you're running into.

**Comment by bede** [comment]
Thanks Nate. Unfortunately I cannot provide this since these reports came from several users without proper conditions to reproduce. For these users PyCountry was running under PyInstaller. Since then we've frozen PyCountry into the static JSON assets which we distribute inside package_data and no problems have been reported. I suspect there is an incompatibility with PyInstaller on Windows, hence my seeking clarification in order to determine whether even CPython is supported.

Feel free to close, but I do think that stating OS support somewhere would be a good move for the project.

**Comment by nschimmoller** [comment]
@bede totally understand and agree also that this could be helpful in the documentation. I'm not too positive how to go about validating this as a user myself / aspiring contributor short of spinning up a VM as I personally own a Mac. Also as just another user not able to close the issue out myself. Doing some research online seems like there are some other users who have had similar issues but found workarounds:

[PyCountry via pipenv](https://github.com/pypa/pipenv/issues/3245)
[PyCountry via PyInstaller](https://stackoverflow.com/questions/63920884/pyinstaller-not-working-with-module-pycountry)

It seems as though the latter of those two links is trying to reference [this Google Groups conversation](https://groups.google.com/g/pyinstaller/c/OYhJdeZ9010/m/vLhYAWUzAQAJ) that is no longer supported via embedding. I may poke around this conversation a bit more to see if it's something I could make a commit to address.

**Comment by ctheune** [comment]
Honestly, I'm not against pycountry running on windows, but the specified issue completely leave me mystified and as I have no idea what's going on there, I think i'm going to close this.
