### ISSUE TITLE
Shouldn't project resource files belong into resources instead of src?

### ISSUE THREAD

**Issue by stefan-bordag** [flyingcircusio/pycountry#118]
I am building a project, which uses [schwifty](https://github.com/mdomke/schwifty), which in turn uses pycountry. The problem is that pycountry throws the warning messages, as seen below. The reason for that is that the "src" folder contains resources, which are not python sources. Instead, they are necessary data files. Since they are not sources, the pycountry structure does not carry __init__.py files in each of these "packages" (Python considers folders to be packages). This is correct. But since all of this is is located in src, certain parts of python are getting confused about this :)

I'd offer to make a pull request to remedy the situation. But I am not aware of any further dependencies which might, for example, ignore the python source code and look for the files directly. Or maybe there is a different solution to avoid the mentioned warnings when using the project?

```
check.warn(importable)
  /tmp/pip-build-env-hq4af0t7/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:153: SetuptoolsDeprecationWarning:     Installing 'pycountry.locales.ta.LC_MESSAGES' as data is deprecated, please list it in `packages`.
      !!
      ############################
      # Package would be ignored #
      ############################
      Python recognizes 'pycountry.locales.ta.LC_MESSAGES' as an importable package,
      but it is not listed in the `packages` configuration of setuptools.
      'pycountry.locales.ta.LC_MESSAGES' has been automatically added to the distribution only
      because it may contain data files, but this behavior is likely to change
      in future versions of setuptools (and therefore is considered deprecated).
      Please make sure that 'pycountry.locales.ta.LC_MESSAGES' is included as a package by using
      the `packages` configuration field or the proper discovery methods
      (for example by using `find_namespace_packages(...)`/`find_namespace:`
      instead of `find_packages(...)`/`find:`).
      You can read more about "package discovery" and "data files" on setuptools
      documentation page.
  !!
```

**Comment by stefan-bordag** [comment]
I went and created a pull request with this in mind. However, since I don't fully understand what pkg_resources really does, it may not be fully correct. All tests pass, though.

See [this pull request](https://github.com/flyingcircusio/pycountry/pull/119).

**Comment by nschimmoller** [comment]
@stefan-bordag my rudimentary understanding is that PyCountry is primarily installed by users via pip. The current [setup.py](https://github.com/flyingcircusio/pycountry/blob/master/setup.py) file at the root of this repo instructs the installation of this package to begin at "src" as seen on [line 47](https://github.com/flyingcircusio/pycountry/blob/e2352cc16c7bd2c3190f56507b4321a57177a7ef/setup.py#L47). Thus everything that is going to be used by the end user has to be past that specific location. 

The rest of the files at the root of the repo are a lot more dev resources than end user ones. Again not an expert, but know enough to maybe break a few things.

**Comment by ofek** [comment]
This is just a build-time warning

**Comment by ofek** [comment]
I made https://github.com/flyingcircusio/pycountry/pull/130 to fix

**Comment by ctheune** [comment]
Yeah, placing the data files outside of src will cause this to break. AFAIK we do not have a separate mechanism to provide data files that go "elsewhere" outside of the regular PYTHONPATH.

Interestingly I haven't seen this setuptools behaviour before and as @ofek mentioned this is a build time warning, likely apparently due to a semantics change in setuptools. As we're switching to a more modern metadata approach I think this will resolve itself then.
