### ISSUE TITLE
Is the order of pycountry.countries guaranteed to stay the same?

### ISSUE THREAD

**Issue by StephenCarboni** [flyingcircusio/pycountry#120]

**Comment by nschimmoller** [comment]
@StephenCarboni it looks as though the ISO 3166-1 file that contains country information is sorted alphabetically based upon alpha_3 codes. Therefore, there is no guarantee given the reality that new countries come and go this will stay in the same order.

**Comment by ctheune** [comment]
Yeah, I wouldn't say there is any guarantee on the order right now.
