### ISSUE TITLE
Tuvalu country missing official_name

### ISSUE THREAD

**Issue by hongquan** [flyingcircusio/pycountry#127]
```py
>>> import pycountry
>>> pycountry.countries.get(alpha_2='TV')
Country(alpha_2='TV', alpha_3='TUV', flag='🇹🇻', name='Tuvalu', numeric='798')
```

**Comment by nschimmoller** [comment]
Hi @hongquan PyCountry is just a wrapper for ISO data as governed by the ISO and as managed by the [Debian database](https://salsa.debian.org/iso-codes-team/iso-codes). I just pulled their most recent release 4.10.0 as seen in PR #124 and Tuvalu does not have an official name in this release either.
