### ISSUE TITLE
Security Issue with some old versions of `pycountry`

### ISSUE THREAD

**Issue by rakovskij-stanislav** [flyingcircusio/pycountry#128]
Hello! Found a security issue in your package on pypi:
https://pypi.org/project/pycountry/

Affected versions:
- 0.15 (released: 22 Jun 2013)
- 0.16 (released 2 Jul 2013)

There's an unmet dependency on module "pytest-capturelog" if you try to install one of these versions (this is `setup.py` file from 0.16):
```python
# vim:fileencoding=utf-8
# Copyright (c) gocept gmbh & co. kg
# See also LICENSE.txt

import os.path
from setuptools import setup, find_packages


setup(
    name='pycountry',
    version='0.16',
    author='Christian Theune',
    author_email='ct@gocept.com',
    description='ISO country, subdivision, language, currency and script '
                'definitions and their translations',
    long_description=(
        open('README').read() + '\n' +
        open('HISTORY.txt').read()),
    license='LGPL 2.1',
    keywords='country subdivision language currency iso 3166 639 4217 '
             '15924 3166-2',
    zip_safe=False,
    packages=find_packages('src'),
    include_package_data=True,
    package_dir={'': 'src'},
    install_requires=[
        'pytest',
        'pytest-capturelog',
        'pytest-codecheckers',
        'pytest-cov'])
```

You can try it using this command:
```
python3 -m pip install --upgrade pycountry==0.16
Collecting pycountry==0.16
  Using cached pycountry-0.16.zip (7.8 MB)
  Preparing metadata (setup.py) ... done
Collecting pytest
  Using cached pytest-7.1.2-py3-none-any.whl (297 kB)
ERROR: Could not find a version that satisfies the requirement pytest-capturelog (from pycountry) (from versions: none)
ERROR: No matching distribution found for pytest-capturelog
```

It's the similar issue like in https://github.com/dmwm/WMCore/issues/11188

It's dangerous because the intruder can create malicious package "pytest-capturelog" on pypi and:
- Make online guides how to use pycountry, using this malicious supply chain attack to compromise users.
- Infect automated CI/CD pipelines that uses old version of pycountry
- Infect other users by hardcoding those versions of package in opensource projects that use pycountry

It's dangerous because usage of pycountry, even outdated, is not something strange. Everyone likes hardcoded versions of packages, even in the era of protestware.

The best solution is to delete 0.15 and 0.16 from pypi. Better to break dependencies in some old pipelines than compromise them.

---

Rakovsky Stanislav (Positive Technologies)

**Comment by ctheune** [comment]
Thanks. Unfortunately PyPI is a bit intransparent here. The package used to exist but isn't currently exposed. PyPI does not allow new registrations for this package.

I created a placeholder for the name and can not register it:

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'pytest-capturelog' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

No worries here. I'm not going to pull the old releases.
