### ISSUE TITLE
Implementation of latest ISO_3166-2:DO

### ISSUE THREAD

**Issue by joseagrc** [flyingcircusio/pycountry#13]
ISO 3166-2 for Dominican Republic was updated in 2015.
See also http://dominicana.gob.do/index.php/e-municipios/e-localidades/2014-12-16-20-41-38
Pull request: #12 
[Division Territorial 2015.pdf](https://github.com/flyingcircusio/pycountry/files/3928465/Division.Territorial.2015.pdf)

**Comment by PanderMusubi** [comment]
@joseagrc this should (also) be reported upstream at https://salsa.debian.org/iso-codes-team/iso-codes/issues (or better add a merge request) if that hasn't been fixed yet in https://salsa.debian.org/iso-codes-team/iso-codes/blob/master/data/iso_3166-2.json

**Comment by ctheune** [comment]
What pander said! :)
