### ISSUE TITLE
Support ISO 639-5 from iso-codes

### ISSUE THREAD

**Issue by PanderMusubi** [flyingcircusio/pycountry#20]
Please see https://bitbucket.org/flyingcircus/pycountry/issues/13376/support-iso-639-5-from-iso-codes for the details

**Comment by PanderMusubi** [comment]
As that repo will be removed: Please support ISO 639-5 for language families and groups.

Proposed implementation was:

    class LanguageFamilies(pycountry.db.Database):
        """Providess access to an ISO 639-5 database (Language Families)."""
    
        field_map = dict(id='id',
                         name='',
                         parents='parents',
                         )
        no_index = ['parents']
        data_class_name = 'Language Family'
        xml_tags = 'iso_639_5_entry'
    
    ...
    
    languages = LanguageFamilies(os.path.join(DATABASE_DIR, 'iso639_5.xml'))
    
    ...
    
        indoeuropeanlanguages = pycountry.languages.get(id='ine')
        assert indoeuropeanlanguages.id == 'ine'
        assert indoeuropeanlanguages.name == 'Indo-European languages'


Note that parents is optional and can contain multiple keys separated by a comma and are not unique. The parents key must not be used as a key in this package, ony by the end user.

**Comment by ctheune** [comment]
Ah, this has been implemented already AFAICT.
