### ISSUE TITLE
Attribute error when querying for ceubano 'ceb" iso code

### ISSUE THREAD

**Issue by datashinobi** [flyingcircusio/pycountry#29]
pycountry==19.8.18
https://iso639-3.sil.org/code/ceb

=============
`from pycountry import languages
languages.get(alpha_2 = 'ceb').name

AttributeError                            Traceback (most recent call last)
<ipython-input-43-61362de1da19> in <module>
      1 from pycountry import languages
      2 print(pycountry.Languages)
----> 3 languages.get(alpha_2 = 'ceb').name

AttributeError: 'NoneType' object has no attribute 'name'
`

**Comment by ctheune** [comment]
Small mistake in the example code: 'CEB' has three letters and is an alpha_3 code. Using alpha_3 works. (At least on the current trunk which will be released in the next minutes, not sure whether this data was touched in the last months).
