### ISSUE TITLE
Missing MX-CMX from Mexico subdivisions

### ISSUE THREAD

**Issue by ljavalysos** [flyingcircusio/pycountry#31]
The ISO-3166 standard changed the subdivision code MX-DIF to MX-CMX as of 2016-11-15. This is listed in the change history at the bottom of the page [here](https://www.iso.org/obp/ui/#iso:code:3166:MX).

Currently, searching pycountry subdivisions for MX-CMX turns up a KeyError indicating it's not found. Can you update the source list with the new subdivision code?

Also, I find it concerning that in this instance the ISO change was made several years ago. How often are those changes propagated to the library? Are we unable to assume that pycountry reflects the most recent ISO-3166 standard?

**Comment by ljavalysos** [comment]
@ctheune any updates on this?

**Comment by ef2k** [comment]
bump  :)

**Comment by ctheune** [comment]
Please report data quality issues upstream:
https://salsa.debian.org/iso-codes-team/iso-codes/-/issues

Thanks!
