### ISSUE TITLE
Kosovo missing

### ISSUE THREAD

**Issue by nanorules** [flyingcircusio/pycountry#45]
Hi,

Kosovo has declared independance in 2008 and I think most software this days include them in their countries list.

**Comment by ctheune** [comment]
Please review the first paragraphs about data changes:

```
Data update policy

No changes to the data will be accepted into pycountry. This is a pure wrapper around the ISO standard using the pkg-isocodes database from Debian as is. If you need changes to the political situation in the world, please talk to the ISO or Debian people, not me.
```

**Comment by ivictbor** [comment]
Related discussion: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=872867
