### ISSUE TITLE
Missing Country Code alpha 2 mappings for some of the country names

### ISSUE THREAD

**Issue by DomDomDoy** [flyingcircusio/pycountry#56]
`{ country.name: country.alpha_2 for country in pycountry.countries }`
A couple missing alpha 2 codes I noticed while creating a dictionary that are missing that might wanna be added

Hong Kong SAR China -> HR
Russia -> RU
South Korea -> KR
Taiwan -> TW
Venezuela -> VE
Vietnam -> VN
Czech Republic -> CZ (entry for Czechia exists however)

**Comment by ctheune** [comment]
I think this was a data problem, afaict this should be fixed in upstream now.
