### ISSUE TITLE
Implementation of latest ISO_3166-2:TW

### ISSUE THREAD

**Issue by engerim42** [flyingcircusio/pycountry#6]
ISO 3166 Maintenance Agency (ISO 3166/MA) has updated in 2016 and late 2018.
See also https://www.iso.org/obp/ui/#iso:code:3166:TW
Pull request: https://github.com/flyingcircusio/pycountry/pull/7

**Comment by PanderMusubi** [comment]
@engerim42 this should (also) be reported upstream at https://salsa.debian.org/iso-codes-team/iso-codes/issues (or better perge request) if that hasn't been fixed yet in https://salsa.debian.org/iso-codes-team/iso-codes/blob/master/data/iso_3166-2.json

**Comment by ctheune** [comment]
Pander is right. I updated to 4.5.0 just today.
