### ISSUE TITLE
PL subdivisions changed in 2018

### ISSUE THREAD

**Issue by massimocandela** [flyingcircusio/pycountry#78]
Hi,

Currently the ISO 3166-2 codes for Poland are wrong. Example: https://github.com/flyingcircusio/pycountry/blob/b1ba295611fbefb9797c97e06293838b8d4f4df3/src/pycountry/databases/iso3166-2.json#L18952
See https://www.iso.org/obp/ui/#iso:code:3166:PL for more information:

```
Change of subdivision code from PL-DS to PL-02, PL-KP to PL-04, PL-LB to PL-08, PL-LD to PL-10, PL-LU to PL-06, PL-MA to PL-12, PL-MZ to PL-14, PL-OP to PL-16, PL-PD to PL-20, PL-PK to PL-18, PL-PM to PL-22, PL-SK to PL-26, PL-SL to PL-24, PL-WN to PL-28, PL-WP to PL-30 and PL-ZP to PL-32; 
```

**Comment by ctheune** [comment]
This is a great idea and I think I should consider that when working on #97 . OTOH that would cause runtime dependencies instead of build time dependencies ... 

I just updated to iso codes 4.9 so maybe the specific issue is solved.
