### ISSUE TITLE
Lookup always uses slow path

### ISSUE THREAD

**Issue by fbergen** [flyingcircusio/pycountry#8]
In the lookup code we always lower case the lookup string `value`, this results in the quick exact match lookup to always fail since we don't lowercase while creating the indices.

I see two potential solutions:
1/ Always lowercase index keys [could this be dangerous for some inputs?]
2/ Don't lowercase before index lookups (similar to what we do in get)

ref: https://github.com/flyingcircusio/pycountry/blob/master/src/pycountry/db.py#L122
```
    def lookup(self, value):
        # try relatively quick exact matches first
        if isinstance(value, (str, unicode)):
            value = value.lower()

        for key in self.indices:
            try:
                return self.indices[key][value]
            except LookupError:
                pass
```

**Comment by ctheune** [comment]
Yeah, that was stupid and fixed in PR #9. Reviewing this also made me write another test case for the slow path as that wasn't
covered anymore - and thus obviously broke right away...
