### ISSUE TITLE
Edge Case Dsicovery: 'Korea South' and 'U.S.A.'

### ISSUE THREAD

**Issue by BradKML** [flyingcircusio/pycountry#84]
This problem is discovered when playing around with the data in https://www.kaggle.com/tarukofusuki/hofstede-s-cultural-dimensions-notebook/data

**Comment by BrandonKMLee** [comment]
More Edge Cases from https://raw.githubusercontent.com/Christoph/Happiness-Teaching-Dataset/master/happiness_development.csv
- Northern Cyprus
- Hong Kong S.A.R., China
- Palestinian Territories
- Congo (Brazzaville)
- Congo (Kinshasa)
- Ivory Coast

For some of the items like Northern Cyprus and Palestinian territories, it belongs with https://github.com/flyingcircusio/pycountry/issues/70

**Comment by 0x802** [comment]
where is `Palestinian Territories` !!
