### ISSUE TITLE
Philipines is not in the list

### ISSUE THREAD

**Issue by MAFiA303** [flyingcircusio/pycountry#90]
`pycountry.countries.get(alpha_2=str('PI'))`
returns nothing
while other countries like:
`pycountry.countries.get(alpha_2=str('PL'))`

returns 
`Country(alpha_2='PL', alpha_3='POL', name='Poland', numeric='616', official_name='Republic of Poland')`

**Comment by lordwelch** [comment]
```py
>>> import pycountry
>>> pycountry.countries.get(alpha_2=str('PH'))
Country(alpha_2='PH', alpha_3='PHL', flag='🇵🇭', name='Philippines', numeric='608', official_name='Republic of the Philippines')
```
